apiVersion: samplecontroller.scc.com/v1alpha1
kind: Scc
metadata:
  name: scc-example
  namespace: default
spec:
  deploymentConfig:
    name: scr
    replicas: 7
    image: nginx
  serviceConfig:
    type: NodePort
    port: 4444
  deletionPolicy: WipeOut
